# Generated code do not commit.
file(TO_CMAKE_PATH "E:\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "E:\\extropos" PROJECT_DIR)

set(FLUTTER_VERSION "1.1.2+30" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 2 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 30 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=E:\\flutter"
  "PROJECT_DIR=E:\\extropos"
  "FLUTTER_ROOT=E:\\flutter"
  "FLUTTER_EPHEMERAL_DIR=E:\\extropos\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=E:\\extropos"
  "FLUTTER_TARGET=E:\\extropos\\lib/main.dart"
  "DART_DEFINES=RkxVVFRFUl9BUFBfRkxBVk9SPXBvc0FwcA==,RkxVVFRFUl9WRVJTSU9OPTMuMzguOQ==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NjczMjNkZTI4NQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NTg3YzE4Zjg3Mw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMC44"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=E:\\extropos\\.dart_tool\\package_config.json"
  "FLAVOR=posApp"
)
